minidlna:  * fix static linking of minidlna fails if uClibc-0.9.28 based toolchain is used {{{ utils.c:(.text+0x37e4): undefined reference to `libiconv_open' utils.c:(.text+0x37ec): undefined reference to `libiconv_open' utils.c:(.text+0x38a8): undefined reference to `libiconv' utils.c:(.text+0x38d0): undefined reference to `libiconv' utils.c:(.text+0x38e0): undefined reference to `libiconv' utils.c:(.text+0x38f8): undefined reference to `libiconv' utils.c:(.text+0x3ad0): undefined reference to `libiconv_close' utils.c:(.text+0x3ad4): undefined reference to `libiconv_close' collect2: ld returned 1 exit status }}}
git-svn-id: file:///var/svn/freetz/trunk@12878 149334a1-2f27-0410-a3b9-fc62619ac1e6